{{- if .Values.headscale.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.headscale.secret.name }}
  {{- with .Values.headscale.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  #only add if oidc is set
  {{- if .Values.headscale.config.oidc }}
  {{- if .Values.headscale.secret.oidc.client_secret}}
  HEADSCALE_OIDC_CLIENT_SECRET: {{ .Values.headscale.secret.oidc.client_secret | b64enc | quote}}
  {{- end }}
{{- end }}
{{- end }}
