---
apiVersion: v1
kind: Secret
metadata:
  name: headscale-config
type: Opaque
stringData:
  config.yaml: |
{{- toYaml .Values.headscale.config | nindent 4 }}
{{- if .Values.headscale.oidc.enabled }}
    oidc:
      issuer: {{ .Values.headscale.oidc.issuer | quote }}
      client_id: {{ .Values.headscale.oidc.client_id | quote }}
      {{- if .Values.headscale.oidc.allowed_groups }}
      allowed_groups:
        {{- toYaml .Values.headscale.oidc.allowed_groups | nindent 8 }}
      {{- end }}
      {{- if .Values.headscale.oidc.allowed_domains }}
      allowed_domains:
        {{- toYaml .Values.headscale.oidc.allowed_domains | nindent 8 }}
      {{- end }}
      {{- if .Values.headscale.oidc.allowed_users }}
      allowed_users:
        {{- toYaml .Values.headscale.oidc.allowed_users | nindent 8 }}
      {{- end }}
{{- end }} 