---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: headplane
  name: headplane
  namespace: headplane
spec:
  ports:
  - name: headscale
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: headplane
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: headplane
  type: ClusterIP
