{{- if .Values.relay.enabled -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tailscale-relay
  labels:
    app: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      serviceAccountName: "tailscale-relay"
      containers:
      - name: tailscale
        image: {{ .Values.relay.image }}
        imagePullPolicy: Always
        env:
        {{- $extraArgs := list }}
        {{- if .Values.relay.config.login_server }}
        {{- $extraArgs = append $extraArgs (printf "--login-server=%s" .Values.relay.config.login_server) }}
        {{- end }}
        {{- if .Values.relay.config.advertise_exit_node }}
        {{- $extraArgs = append $extraArgs "--advertise-exit-node" }}
        {{- end }}
        {{- if gt (len $extraArgs) 0 }}
        - name: TS_EXTRA_ARGS
          value: "{{ join " " $extraArgs }}"
        {{- end }}
        {{- if .Values.relay.config.exit_node }}
        - name: TS_EXIT_NODE
          value: "{{ .Values.relay.config.exit_node }}"
        {{- end }}
        {{- if .Values.relay.config.hostname }}
        - name: TS_HOSTNAME
          value: "{{ .Values.relay.config.hostname }}"
        {{- end }}
        {{- if .Values.relay.config.routes }}
        - name: TS_ROUTES
          value: "{{ .Values.relay.config.routes }}"
        {{- end }}
        {{- if .Values.relay.config.firewall_debug }}
        - name: TS_DEBUG_FIREWALL_MODE
          value: "{{ .Values.relay.config.firewall_debug }}"
        {{- end }}
# Store the state in a k8s secret
        - name: TS_KUBE_SECRET
          value: "tailscale-auth"
        - name: TS_USERSPACE
          value: "true"
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
              optional: true
              optional: true

        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
{{- end }}
