name: Pre-release (next)
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: pre-release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write # Allow canceling in-progress runs
  contents: read # Read access to the repository
  packages: write # Write access to the container registry
  id-token: write # For the attest action to push
  attestations: write # For the attest action to push

jobs:
  publish:
    # Ensure the action only runs if manually dispatched or a PR on the `next` branch in the *main* repository is opened or synchronized.
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.pull_request && github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.head.ref == 'next') }}
    name: Docker Pre-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: final
            tag: 'next'
          - target: debug-shell
            tag: 'next-shell'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ matrix.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish ghcr.io/${{ github.repository }}:${{ matrix.tag }}
        uses: docker/build-push-action@v6
        id: push
        with:
          context: .
          file: ./Dockerfile
          target: ${{ matrix.target }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64, linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            IMAGE_TAG=ghcr.io/${{ github.repository }}:${{ matrix.tag }}
            MISE_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

      - name: Attestation Provenance for ghcr.io/${{ github.repository }}:${{ matrix.tag }}
        uses: actions/attest-build-provenance@v2
        id: attest
        with:
          subject-name: ghcr.io/${{ github.repository }}:${{ matrix.tag }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
